#!/bin/bash

# INSTALL REQUIRED LIBS
apt-get update -q
apt-get install -q sudo libpam-winbind libnss-winbind libpam-krb5 -y

###########################################################################################
# GET CONFIG
REALM=$(cat /etc/krb5.conf | grep default_realm | cut -s -d '=' -f 2 | sed 's/\ //g')
WORKGROUP=$(echo $REALM | cut -s -d '.' -f 1)

###########################################################################################
## CHECK REALM
krb5_dns_error(){
    echo "Can't find $REALM realm with current Kerberos and/or DNS settings :( Aborting..."
    echo "You can reconfigure Kerberos with <dpkg-reconfigure -plow krb5-config>."
    echo "Your DNS settings:"
    cat /etc/resolv.conf
    exit 1
}
ping $REALM -c1 -qq 2>&1 >&- || krb5_dns_error

###########################################################################################
## PAM: mkhomedir
echo 'Name: Make home directory for user
Default: yes
Priority: 192
Session-Type: Additional
Session-Interactive-Only: yes
Session:
    optional						pam_mkhomedir.so' > /usr/share/pam-configs/mkhomedir

## PAM: Reconfigure
sed -i 's/winbind//g;s/mkhomedir//g;s/krb5//g;/^$/d' /var/lib/pam/seen
dpkg-reconfigure -phigh libpam-runtime

###########################################################################################
## SAMBA
service winbind stop > /dev/null
service smbd stop > /dev/null
###
echo "# AUTOGENERATED CONFIGURATION FILE! PLEASE USE /etc/samba/samba.conf.local FOR YOUR SETTINGS!

[global]
	workgroup = $WORKGROUP
	realm = $REALM
	security = ADS
	load printers = No
	printcap name = /dev/null
	disable spoolss = Yes
	show add printer wizard = No
	os level = 0
	local master = No
	domain master = No
	dns proxy = No

	winbind use default domain = Yes
	winbind nss info = rfc2307
	winbind nested groups = yes
	winbind enum users = Yes
	winbind enum groups = Yes
	winbind refresh tickets = Yes

	idmap config $WORKGROUP : default = yes
	idmap config $WORKGROUP : schema_mode = rfc2307
	idmap config $WORKGROUP : backend = ad
	idmap config $WORKGROUP : range = 10000 - 9999999999

	idmap config * : backend = tdb
	idmap config * : range = 1001 - 9999

	map to guest = Bad Password


# INCLUDE LOCAL CONFIGURATION
	include = /etc/samba/smb.conf.local" > /etc/samba/smb.conf
###
SMB_LOCAL_SUFFIX=''
if [ -f /etc/samba/smb.conf.local ]; then
    SMB_LOCAL_SUFFIX='.new'
fi
###
echo "# LOCAL CONFIGURATION FILE

	winbind offline logon = no
#		winbind cache time = 300

	template homedir = /home/%U
#		template shell = /bin/bash

	debug level = 10
	log level = 10" > /etc/samba/smb.conf.local${SMB_LOCAL_SUFFIX}
###
service smbd start > /dev/null
service winbind start > /dev/null

###########################################################################################
## SUDOERS ##
echo "# Grant domain admins all rights
%Domain\x20Admins ALL=(ALL) ALL" > /etc/sudoers.d/domain-admins

###########################################################################################
## NSSWITCH.CONF ##
FILE=/etc/nsswitch.conf
ITEMS="passwd group"
ADDON="winbind"
for ITEM in $ITEMS; do
    IN_NSSWITCH="$(cat $FILE | grep ^$ITEM: | grep -v $ADDON)"
    if [ -n "${IN_NSSWITCH}" ]; then
	IN_NSSWITCH_SED="$(echo ${IN_NSSWITCH} | cut -s -d ':' -f 2- | sed 's/^[ ^t]*//;s/[ ^]*$//;s/\ /\\ /g')"
	sed -e "/^$ITEM/s/$IN_NSSWITCH_SED/$IN_NSSWITCH_SED\ $ADDON/g" -i $FILE
    fi
done

###########################################################################################
## END ##
echo "Using realm $REALM from /etc/krb5.conf"
echo "---------------------------------------------------------------------"
echo "Joining domain $REALM now..."
net ads join -U administrator -D $REALM && service smbd restart > /dev/null ; service winbind restart > /dev/null
